"""Country-level location checks for provider results."""

import re

from app.models import normalize

# Provider cards often include a city and country in a localized string. We only
# need to reject an explicit non-French country here; city-only results from a
# France-scoped search remain eligible.
_NON_FRANCE_COUNTRIES = {
    "afghanistan",
    "afrique du sud",
    "albania",
    "albanie",
    "algeria",
    "algerie",
    "allemagne",
    "andorra",
    "andorre",
    "angola",
    "argentina",
    "argentine",
    "armenia",
    "armenie",
    "australia",
    "australie",
    "austria",
    "autriche",
    "azerbaijan",
    "azerbaidjan",
    "bahamas",
    "bangladesh",
    "belarus",
    "belgique",
    "belgium",
    "bolivia",
    "bolivie",
    "bosnia and herzegovina",
    "bosnie herzegovine",
    "brazil",
    "bresil",
    "bulgaria",
    "bulgarie",
    "cambodia",
    "cambodge",
    "cameroon",
    "cameroun",
    "canada",
    "chile",
    "chili",
    "china",
    "chine",
    "colombia",
    "colombie",
    "coree du sud",
    "costa rica",
    "croatia",
    "croatie",
    "cuba",
    "cyprus",
    "chypre",
    "czech republic",
    "czechia",
    "republique tcheque",
    "danemark",
    "denmark",
    "dominican republic",
    "republique dominicaine",
    "egypt",
    "egypte",
    "emirats arabes unis",
    "estonia",
    "estonie",
    "ethiopia",
    "ethiopie",
    "finland",
    "finlande",
    "georgia",
    "georgie",
    "germany",
    "ghana",
    "greece",
    "grece",
    "hong kong",
    "hongrie",
    "hungary",
    "iceland",
    "islande",
    "india",
    "inde",
    "indonesia",
    "indonesie",
    "iran",
    "iraq",
    "irak",
    "ireland",
    "irlande",
    "israel",
    "italie",
    "italy",
    "japan",
    "japon",
    "jordan",
    "jordanie",
    "kazakhstan",
    "kenya",
    "kosovo",
    "kuwait",
    "latvia",
    "lettonie",
    "liban",
    "lebanon",
    "libya",
    "libye",
    "lithuania",
    "lituanie",
    "luxembourg",
    "malaysia",
    "malaisie",
    "malta",
    "malte",
    "mexico",
    "mexique",
    "morocco",
    "maroc",
    "nepal",
    "netherlands",
    "pays bas",
    "new zealand",
    "nouvelle zelande",
    "nigeria",
    "north macedonia",
    "norway",
    "norvege",
    "oman",
    "pakistan",
    "palestine",
    "peru",
    "perou",
    "philippines",
    "pologne",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "roumanie",
    "russia",
    "russie",
    "saudi arabia",
    "arabie saoudite",
    "scotland",
    "ecosse",
    "senegal",
    "serbia",
    "serbie",
    "singapore",
    "singapour",
    "slovakia",
    "slovaquie",
    "slovenia",
    "slovenie",
    "south africa",
    "south korea",
    "south sudan",
    "spain",
    "espagne",
    "sri lanka",
    "sweden",
    "suede",
    "switzerland",
    "suisse",
    "syria",
    "syrie",
    "taiwan",
    "thailand",
    "thailande",
    "tunisia",
    "tunisie",
    "turkey",
    "turquie",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "usa",
    "venezuela",
    "vietnam",
    "viet nam",
    "wales",
    "zambia",
    "zimbabwe",
    "angleterre",
    "england",
    "great britain",
    "britain",
    "uk",
    "usa",
    "united states of america",
    "royaume uni",
}

_COUNTRY_PATTERNS = tuple(
    re.compile(r"(?<!\w)" + re.escape(country) + r"(?!\w)")
    for country in sorted(_NON_FRANCE_COUNTRIES, key=len, reverse=True)
)


def is_french_location(location: str, country_code: str | None = None) -> bool:
    """Reject explicitly foreign listings while allowing city-only French results."""
    if country_code:
        return country_code.strip().upper() == "FR"
    value = normalize(location)
    return not any(pattern.search(value) for pattern in _COUNTRY_PATTERNS)
